// 4. Write a dart program to print your name 100 times.

void main(){
    String name = "Sunjir Islam Sanuj";
    for (int i=0; i<100; i++) print(name);
}

/* Output:
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj
Sunjir Islam Sanuj */